### ISSUE TITLE
Assertion with pt-online-schema-change

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#135]
Using pt-online-schema-change results in either of the following:
1. Hang, two threads blocked in "Waiting for table metadata lock", seems permanently.
2. Assertion:

```
#7  0x0000003e9042da82 in __assert_fail () from /lib64/libc.so.6
#8  0x000000000089c3da in Table_cache_manager::free_table (this=0x17fd240 <table_cache_manager>, thd=0x37f6a60, remove_type=TDC_RT_REMOVE_NOT_OWN, share=0x7f593c00b030) at /home/philips/git/mysql-wsrep/sql/table_cache.cc:372
#9  0x000000000077e4ca in tdc_remove_table (thd=0x37f6a60, remove_type=TDC_RT_REMOVE_NOT_OWN, db=0x7f593c00b350 "test", table_name=0x7f593c00b355 "t1", has_lock=false) at /home/philips/git/mysql-wsrep/sql/sql_base.cc:9330
#10 0x0000000000770d50 in wait_while_table_is_used (thd=0x37f6a60, table=0x7f593c039840, function=HA_EXTRA_FORCE_REOPEN) at /home/philips/git/mysql-wsrep/sql/sql_base.cc:2297
#11 0x000000000085bc0d in mysql_create_or_drop_trigger (thd=0x37f6a60, tables=0x7f5928004ed0, create=true) at /home/philips/git/mysql-wsrep/sql/sql_trigger.cc:553
#12 0x00000000007e0cc7 in mysql_execute_command (thd=0x37f6a60) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:5249
#13 0x00000000007e5220 in mysql_parse (thd=0x37f6a60, rawbuf=0x7f5928004c50 "CREATE TRIGGER `pt_osc_test_t1_upd` AFTER UPDATE ON `test`.`t1` FOR EACH ROW REPLACE INTO `test`.`_t1_new` (`f1`) VALUES (NEW.`f1`)", length=131, parser_state=0x7f5968ff86e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6976
#14 0x00000000007e467e in wsrep_mysql_parse (thd=0x37f6a60, rawbuf=0x7f5928004c50 "CREATE TRIGGER `pt_osc_test_t1_upd` AFTER UPDATE ON `test`.`t1` FOR EACH ROW REPLACE INTO `test`.`_t1_new` (`f1`) VALUES (NEW.`f1`)", length=131, parser_state=0x7f5968ff86e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6723
#15 0x00000000007d655f in dispatch_command (command=COM_QUERY, thd=0x37f6a60, packet=0x38c21e1 "CREATE TRIGGER `pt_osc_test_t1_upd` AFTER UPDATE ON `test`.`t1` FOR EACH ROW REPLACE INTO `test`.`_t1_new` (`f1`) VALUES (NEW.`f1`)", packet_length=131) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1526
#16 0x00000000007d50ae in do_command (thd=0x37f6a60) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1115
#17 0x00000000007a0c25 in do_handle_one_connection (thd_arg=0x37f6a60) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:1007
#18 0x00000000007a075b in handle_one_connection (arg=0x37f6a60) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:916
#19 0x0000000000acb71b in pfs_spawn_thread (arg=0x378fcc0) at /home/philips/git/mysql-wsrep/storage/perfschema/pfs.cc:1860
#20 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#21 0x0000003e905045fd in clone () from /lib64/libc.so.6
```
1. Excessive log output:

```
2015-05-26 08:47:07 22840 [Note] WSREP: MDL BF-BF conflict
request: (2     seqno 396       wsrep (1, 1, 0) cmd 0 133       (null))
granted: (9     seqno 395       wsrep (2, 1, 0) cmd 3 101       CREATE TRIGGER `pt_osc_test_t1_upd` AFTER UPDATE ON `test`.`t1` FOR EACH ROW REPLACE INTO `test`.`_t1_new` (`f1`) VALUES (NEW.`f1`))
2015-05-26 08:47:07 22840 [Note] WSREP: MDL BF-BF conflict
request: (9     seqno 395       wsrep (2, 1, 0) cmd 3 101       CREATE TRIGGER `pt_osc_test_t1_upd` AFTER UPDATE ON `test`.`t1` FOR EACH ROW REPLACE INTO `test`.`_t1_new` (`f1`) VALUES (NEW.`f1`))
granted: (2     seqno 396       wsrep (1, 0, 0) cmd 0 133       (null))
```

followed by thousands of entries:

```
2015-05-26 08:39:56 21913 [Warning] WSREP: thd 7 seqno 494: conflict state 3 after post commit
2015-05-26 08:39:56 21913 [Warning] WSREP: thd 7 seqno 507: conflict state 3 after post commit
2015-05-26 08:39:56 21913 [Warning] WSREP: thd 7 seqno 509: conflict state 3 after post commit
2015-05-26 08:39:56 21913 [Warning] WSREP: thd 7 seqno 510: conflict state 3 after post commit
2015-05-26 08:39:56 21913 [Warning] WSREP: thd 7 seqno 512: conflict state 3 after post commit
```

**Comment by philip-galera** [comment]
To reproduce:
1. Install pt-online-schema-change from percona:

https://www.percona.com/doc/percona-toolkit/2.0/installation.html
1. Run test case:

```
--source include/big_test.inc
--source include/galera_cluster.inc
--source include/have_innodb.inc

--connection node_1
CREATE TABLE t1 (f1 INTEGER PRIMARY KEY AUTO_INCREMENT) ENGINE=InnoDB;

# A stored procedure that issues 10K autoincrement autocommit inserts

DELIMITER |;
CREATE PROCEDURE p1 ()
BEGIN
        DECLARE x INT DEFAULT 20000;
        DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;

        WHILE x > 0 DO
                SET x = x - 1;
                INSERT INTO t1 (f1) VALUES (DEFAULT);
                COMMIT;
        END WHILE;
END|
DELIMITER ;|

--send CALL p1();

--connection node_2
--send CALL p1();

--connect node_1a, 127.0.0.1, root, , test, $NODE_MYPORT_1
--connection node_1a
--exec pt-online-schema-change --execute --alter "ADD COLUMN f2 INT" u=root,D=test,t=t1,h=127.0.0.1:$NODE_MYPORT_1 </dev/null >/dev/null

--connection node_1
--reap

--connection node_2
--reap

SELECT COUNT(*) = 2 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 't1';
SELECT COUNT(*) > 0 FROM t1;

--connection node_1

SELECT COUNT(*) = 2 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'test' AND TABLE_NAME = 't1';
SELECT COUNT(*) > 0 FROM t1;

DROP PROCEDURE p1;
DROP TABLE t1;
```

**Comment by philip-galera** [comment]
Here is a hang that is observed with the test:

```
Thread 2 (Thread 0x7f1488783700 (LWP 27653)):
#0  0x0000003e90c0cbd0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f149754ce85 in galera::Monitor<galera::ReplicatorSMM::CommitOrder>::enter(galera::ReplicatorSMM::CommitOrder&) () from /usr/lib64/galera/libgalera_smm.so
#2  0x00007f1497547478 in galera::ReplicatorSMM::pre_commit(galera::TrxHandle*, wsrep_trx_meta*) () from /usr/lib64/galera/libgalera_smm.so
#3  0x00007f1497557cd0 in galera_pre_commit () from /usr/lib64/galera/libgalera_smm.so
#4  0x00000000008c04bb in wsrep_run_wsrep_commit (thd=0x1e5e980, hton=0x1adc250, all=false) at /home/philips/git/mysql-wsrep/sql/wsrep_hton.cc:450
#5  0x00000000008bf0da in wsrep_prepare (hton=0x1adc250, thd=0x1e5e980, all=false) at /home/philips/git/mysql-wsrep/sql/wsrep_hton.cc:175
#6  0x000000000064cf7b in ha_prepare_low (thd=0x1e5e980, all=false) at /home/philips/git/mysql-wsrep/sql/handler.cc:2176
#7  0x000000000071e72f in TC_LOG_DUMMY::prepare (this=0x17db4a8 <tc_log_dummy>, thd=0x1e5e980, all=false) at /home/philips/git/mysql-wsrep/sql/log.h:137
#8  0x000000000064b526 in ha_commit_trans (thd=0x1e5e980, all=false, ignore_global_read_lock=false) at /home/philips/git/mysql-wsrep/sql/handler.cc:1469
#9  0x000000000089d90f in trans_commit_stmt (thd=0x1e5e980) at /home/philips/git/mysql-wsrep/sql/transaction.cc:473
#10 0x00000000007e177e in mysql_execute_command (thd=0x1e5e980) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:5460
#11 0x0000000000976838 in sp_instr_stmt::exec_core (this=0x7f14580b2558, thd=0x1e5e980, nextp=0x7f1488781068) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:901
#12 0x00000000009756dd in sp_lex_instr::reset_lex_and_exec_core (this=0x7f14580b2558, thd=0x1e5e980, nextp=0x7f1488781068, open_tables=false) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:390
#13 0x0000000000975fd4 in sp_lex_instr::validate_lex_and_execute_core (this=0x7f14580b2558, thd=0x1e5e980, nextp=0x7f1488781068, open_tables=false) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:638
#14 0x00000000009764d9 in sp_instr_stmt::execute (this=0x7f14580b2558, thd=0x1e5e980, nextp=0x7f1488781068) at /home/philips/git/mysql-wsrep/sql/sp_instr.cc:808
#15 0x000000000073c982 in sp_head::execute (this=0x7f14580aa660, thd=0x1e5e980, merge_da_on_success=true) at /home/philips/git/mysql-wsrep/sql/sp_head.cc:645
#16 0x000000000073e601 in sp_head::execute_procedure (this=0x7f14580aa660, thd=0x1e5e980, args=0x1e61938) at /home/philips/git/mysql-wsrep/sql/sp_head.cc:1315
#17 0x00000000007dff1c in mysql_execute_command (thd=0x1e5e980) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:5003
#18 0x00000000007e5220 in mysql_parse (thd=0x1e5e980, rawbuf=0x7f1458004fd0 "CALL p1()", length=9, parser_state=0x7f14887826e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6976
#19 0x00000000007e467e in wsrep_mysql_parse (thd=0x1e5e980, rawbuf=0x7f1458004fd0 "CALL p1()", length=9, parser_state=0x7f14887826e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6723
#20 0x00000000007d655f in dispatch_command (command=COM_QUERY, thd=0x1e5e980, packet=0x1f2a971 "CALL p1();", packet_length=10) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1526
#21 0x00000000007d50ae in do_command (thd=0x1e5e980) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1115
#22 0x00000000007a0c25 in do_handle_one_connection (thd_arg=0x1e5e980) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:1007
#23 0x00000000007a075b in handle_one_connection (arg=0x1e5e980) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:916
#24 0x0000000000acb71b in pfs_spawn_thread (arg=0x1dae420) at /home/philips/git/mysql-wsrep/storage/perfschema/pfs.cc:1860
#25 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#26 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

and

```
Thread 19 (Thread 0x7f148ab85700 (LWP 27519)):
#0  0x0000003e90c0cbd0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000071f4e0 in inline_mysql_cond_wait (that=0x7f1478000ab8, mutex=0x7f1478000a88, src_file=0xf3ccb8 "/home/philips/git/mysql-wsrep/sql/mdl.cc", src_line=1340) at /home/philips/git/mysql-wsrep/include/mysql/psi/mysql_thread.h:1151
#2  0x00000000007203ae in MDL_wait::timed_wait (this=0x7f1478000a88, owner=0x7f14780009a0, abs_timeout=0x7f148ab80c80, set_status_on_timeout=false, wait_state_name=0x14da5f0 <MDL_key::m_namespace_to_wait_state_name+48>) at /home/philips/git/mysql-wsrep/sql/mdl.cc:1340
#3  0x0000000000721d3b in MDL_context::acquire_lock (this=0x7f1478000a88, mdl_request=0x7f14780091f0, lock_wait_timeout=31536000) at /home/philips/git/mysql-wsrep/sql/mdl.cc:2356
#4  0x0000000000722194 in MDL_context::acquire_locks (this=0x7f1478000a88, mdl_requests=0x7f148ab80fd0, lock_wait_timeout=31536000) at /home/philips/git/mysql-wsrep/sql/mdl.cc:2467
#5  0x00000000007751d7 in lock_table_names (thd=0x7f14780009a0, tables_start=0x7f1478008e50, tables_end=0x0, lock_wait_timeout=31536000, flags=0) at /home/philips/git/mysql-wsrep/sql/sql_base.cc:4881
#6  0x00000000007754f2 in open_tables (thd=0x7f14780009a0, start=0x7f148ab81120, counter=0x7f148ab81164, flags=0, prelocking_strategy=0x7f148ab81200) at /home/philips/git/mysql-wsrep/sql/sql_base.cc:5051
#7  0x000000000077662d in open_and_lock_tables (thd=0x7f14780009a0, tables=0x7f1478008e50, derived=false, flags=0, prelocking_strategy=0x7f148ab81200) at /home/philips/git/mysql-wsrep/sql/sql_base.cc:5744
#8  0x000000000077615a in open_n_lock_single_table (thd=0x7f14780009a0, table_l=0x7f1478008e50, lock_type=TL_READ_NO_INSERT, flags=0, prelocking_strategy=0x7f148ab81200) at /home/philips/git/mysql-wsrep/sql/sql_base.cc:5596
#9  0x0000000000860a79 in open_n_lock_single_table (thd=0x7f14780009a0, table_l=0x7f1478008e50, lock_type=TL_READ_NO_INSERT, flags=0) at /home/philips/git/mysql-wsrep/sql/sql_base.h:461
#10 0x000000000085bb9c in mysql_create_or_drop_trigger (thd=0x7f14780009a0, tables=0x7f1478008e50, create=true) at /home/philips/git/mysql-wsrep/sql/sql_trigger.cc:543
#11 0x00000000007e0cc7 in mysql_execute_command (thd=0x7f14780009a0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:5249
#12 0x00000000007e5220 in mysql_parse (thd=0x7f14780009a0, rawbuf=0x7f147803e528 "CREATE DEFINER=`root`@`localhost` TRIGGER `pt_osc_test_t1_upd` AFTER UPDATE ON `test`.`t1` FOR EACH ROW REPLACE INTO `test`.`_t1_new` (`f1`) VALUES (NEW.`f1`)", length=158, parser_state=0x7f148ab823b0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6976
#13 0x00000000009f07a9 in Query_log_event::do_apply_event (this=0x7f1478068da0, rli=0x7f147800bc30, query_arg=0x7f147803e528 "CREATE DEFINER=`root`@`localhost` TRIGGER `pt_osc_test_t1_upd` AFTER UPDATE ON `test`.`t1` FOR EACH ROW REPLACE INTO `test`.`_t1_new` (`f1`) VALUES (NEW.`f1`)", q_len_arg=158) at /home/philips/git/mysql-wsrep/sql/log_event.cc:4837
#14 0x00000000009efba5 in Query_log_event::do_apply_event (this=0x7f1478068da0, rli=0x7f147800bc30) at /home/philips/git/mysql-wsrep/sql/log_event.cc:4566
#15 0x00000000009ebd6a in Log_event::apply_event (this=0x7f1478068da0, rli=0x7f147800bc30) at /home/philips/git/mysql-wsrep/sql/log_event.cc:3128
#16 0x00000000006404d3 in wsrep_apply_events (thd=0x7f14780009a0, events_buf=0x7f148dd2d134, buf_len=0) at /home/philips/git/mysql-wsrep/sql/wsrep_applier.cc:154
#17 0x0000000000640b3d in wsrep_apply_cb (ctx=0x7f14780009a0, buf=0x7f148dd2d134, buf_len=237, flags=5, meta=0x7f148ab83980) at /home/philips/git/mysql-wsrep/sql/wsrep_applier.cc:251
#18 0x00007f1497506ad8 in galera::TrxHandle::apply(void*, wsrep_cb_status (*)(void*, void const*, unsigned long, unsigned int, wsrep_trx_meta const*), wsrep_trx_meta const&) const () from /usr/lib64/galera/libgalera_smm.so
#19 0x00007f1497542d5d in apply_trx_ws(void*, wsrep_cb_status (*)(void*, void const*, unsigned long, unsigned int, wsrep_trx_meta const*), wsrep_cb_status (*)(void*, unsigned int, wsrep_trx_meta const*, bool*, bool), galera::TrxHandle const&, wsrep_trx_meta const&) () from /usr/lib64/galera/libgalera_smm.so
#20 0x00007f1497545010 in galera::ReplicatorSMM::apply_trx(void*, galera::TrxHandle*) () from /usr/lib64/galera/libgalera_smm.so
#21 0x00007f1497547dfe in galera::ReplicatorSMM::process_trx(void*, galera::TrxHandle*) () from /usr/lib64/galera/libgalera_smm.so
#22 0x00007f1497525528 in galera::GcsActionSource::dispatch(void*, gcs_action const&, bool&) () from /usr/lib64/galera/libgalera_smm.so
#23 0x00007f1497526c9c in galera::GcsActionSource::process(void*, bool&) () from /usr/lib64/galera/libgalera_smm.so
#24 0x00007f1497548323 in galera::ReplicatorSMM::async_recv(void*) () from /usr/lib64/galera/libgalera_smm.so
#25 0x00007f1497556e98 in galera_recv () from /usr/lib64/galera/libgalera_smm.so
#26 0x0000000000642333 in wsrep_replication_process (thd=0x7f14780009a0) at /home/philips/git/mysql-wsrep/sql/wsrep_thd.cc:309
#27 0x00000000006237b9 in start_wsrep_THD (arg=0x642285 <wsrep_replication_process(THD*)>) at /home/philips/git/mysql-wsrep/sql/mysqld.cc:5376
#28 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#29 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

If a timeout applies, it is a very long one.
