### ISSUE TITLE
Cluster inconsistency, assertion after setting wsrep_cluster_address to "gcomm://" and back.

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#139]
Setting wsrep_cluster_address to 'gcomm://', performing some updates, and then setting it back to its original value results in an inconsistent cluster. Future updates fail with:

```
2015-05-28 10:02:24 26572 [ERROR] Slave SQL: Could not execute Delete_rows event on table test.t1; Can't find record in 't1', Error_code: 1032; handler error HA_ERR_END_OF_FILE; the event's master log FIRST, end_log_pos 150, Error_code: 1032
2015-05-28 10:02:24 26572 [Warning] WSREP: RBR event 3 Delete_rows apply warning: 137, 4
mysqld: /home/philips/git/mysql-wsrep/sql/transaction.cc:42: bool trans_check_state(THD*): Assertion `thd->transaction.stmt.is_empty()' failed.

#7  0x0000003e9042da82 in __assert_fail () from /lib64/libc.so.6
#8  0x000000000089c903 in trans_check_state (thd=0x7f708c0009a0) at /home/philips/git/mysql-wsrep/sql/transaction.cc:42
#9  0x000000000089d4d5 in trans_rollback (thd=0x7f708c0009a0) at /home/philips/git/mysql-wsrep/sql/transaction.cc:356
#10 0x0000000000640e4b in wsrep_rollback (thd=0x7f708c0009a0, global_seqno=4) at /home/philips/git/mysql-wsrep/sql/wsrep_applier.cc:322
#11 0x0000000000640f7f in wsrep_commit_cb (ctx=0x7f708c0009a0, flags=1, meta=0x7f709dc71bb0, exit=0x7f709dc716d0, commit=false) at /home/philips/git/mysql-wsrep/sql/wsrep_applier.cc:353
#12 0x00007f70a90df87e in apply_trx_ws (recv_ctx=recv_ctx@entry=0x7f708c0009a0, apply_cb=0x6408b0 <wsrep_apply_cb(void*, void const*, unsigned long, unsigned int, wsrep_trx_meta const*)>, commit_cb=0x640eee <wsrep_commit_cb(void*, unsigned int, wsrep_trx_meta const*, bool*, bool)>, trx=..., meta=...) at galera/src/replicator_smm.cpp:68
#13 0x00007f70a90e22f9 in galera::ReplicatorSMM::apply_trx (this=this@entry=0x1d3bef0, recv_ctx=recv_ctx@entry=0x7f708c0009a0, trx=trx@entry=0x7f708c036bb0) at galera/src/replicator_smm.cpp:433
#14 0x00007f70a90e4a6e in galera::ReplicatorSMM::process_trx (this=0x1d3bef0, recv_ctx=0x7f708c0009a0, trx=0x7f708c036bb0) at galera/src/replicator_smm.cpp:1224
#15 0x00007f70a90cb1d5 in galera::GcsActionSource::dispatch (this=this@entry=0x1d3c570, recv_ctx=recv_ctx@entry=0x7f708c0009a0, act=..., exit_loop=@0x7f709dc7249d: false) at galera/src/gcs_action_source.cpp:116
#16 0x00007f70a90cb679 in galera::GcsActionSource::process (this=0x1d3c570, recv_ctx=0x7f708c0009a0, exit_loop=@0x7f709dc7249d: false) at galera/src/gcs_action_source.cpp:181
#17 0x00007f70a90e5063 in galera::ReplicatorSMM::async_recv (this=0x1d3bef0, recv_ctx=0x7f708c0009a0) at galera/src/replicator_smm.cpp:355
#18 0x0000000000642333 in wsrep_replication_process (thd=0x7f708c0009a0) at /home/philips/git/mysql-wsrep/sql/wsrep_thd.cc:309
#19 0x00000000006237b9 in start_wsrep_THD (arg=0x642285 <wsrep_replication_process(THD*)>) at /home/philips/git/mysql-wsrep/sql/mysqld.cc:5376
#20 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#21 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

**Comment by philip-galera** [comment]
Test case:

```

--source include/galera_cluster.inc
--source include/have_innodb.inc

--connection node_1
CREATE TABLE t1 (f1 INTEGER);
INSERT INTO t1 VALUES (1);

--connection node_2
--let $wsrep_cluster_address_orig = `SELECT @@wsrep_cluster_address`

SET GLOBAL wsrep_cluster_address = 'gcomm://';
--source include/wait_until_connected_again.inc

--connection node_1
--let $wait_condition = SELECT VARIABLE_VALUE = 2 FROM INFORMATION_SCHEMA.GLOBAL_STATUS WHERE VARIABLE_NAME = 'wsrep_cluster_size';
--source include/wait_condition.inc

--connection node_2

INSERT INTO t1 VALUES (2);

--connection node_1
INSERT INTO t1 VALUES (3);

--connection node_2
--disable_query_log
--eval SET GLOBAL wsrep_cluster_address = '$wsrep_cluster_address_orig';
--enable_query_log
--source include/wait_until_connected_again.inc

DELETE FROM t1 WHERE f1 = 2;
```

I think the following should happen:
1. If pc.bootstrap is 0, reconnecting the (by now two) clusters should be disallowed;
2. If pc.bootstrap is 1, then the data from the node where pc.bootstrap is equal to 1 should be replicated to all other nodes.

**Comment by philip-galera** [comment]
```
ok, this is a known issue
[10:09:25] Teemu Ollakka: you did inserts to two nodes in different clusters with same cluster UUID
[10:10:23] Teemu Ollakka: also the number of inserts was the same
[10:10:27] Philip Stoev: should setting gcomm:// generate a new ID?
[10:10:45] Teemu Ollakka: there has been some debate about it
[10:10:53] Teemu Ollakka: currently it does not
[10:10:57] Philip Stoev: ok then
[10:10:59] Teemu Ollakka: IMO it should
```

**Comment by philip-galera** [comment]
Dup of https://github.com/codership/galera/issues/115
