### ISSUE TITLE
Assertion `thd->transaction.stmt.is_empty()' failed in trans_check_state on cluster inconsistency

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#162]
Previously reported as https://bugs.launchpad.net/codership-mysql/+bug/1234395 but now there is a quick MTR test case:

```
#6  0x0000003e9042d9cd in __assert_fail_base () from /lib64/libc.so.6
#7  0x0000003e9042da82 in __assert_fail () from /lib64/libc.so.6
#8  0x000000000089f3af in trans_check_state (thd=0x7fc1cc0009a0) at /home/philips/git/mysql-wsrep/sql/transaction.cc:42
#9  0x000000000089ff81 in trans_rollback (thd=0x7fc1cc0009a0) at /home/philips/git/mysql-wsrep/sql/transaction.cc:356
#10 0x000000000064299d in wsrep_rollback (thd=0x7fc1cc0009a0, global_seqno=2) at /home/philips/git/mysql-wsrep/sql/wsrep_applier.cc:322
#11 0x0000000000642ad1 in wsrep_commit_cb (ctx=0x7fc1cc0009a0, flags=1, meta=0x7fc1e8635bb0, exit=0x7fc1e86356d0, commit=false) at /home/philips/git/mysql-wsrep/sql/wsrep_applier.cc:353
#12 0x00007fc1f2aa1d9e in apply_trx_ws (recv_ctx=recv_ctx@entry=0x7fc1cc0009a0, apply_cb=0x642402 <wsrep_apply_cb(void*, void const*, unsigned long, unsigned int, wsrep_trx_meta const*)>, commit_cb=0x642a40 <wsrep_commit_cb(void*, unsigned int, wsrep_trx_meta const*, bool*, bool)>, trx=..., meta=...) at galera/src/replicator_smm.cpp:68
#13 0x00007fc1f2aa4819 in galera::ReplicatorSMM::apply_trx (this=this@entry=0x2724cb0, recv_ctx=recv_ctx@entry=0x7fc1cc0009a0, trx=trx@entry=0x7fc1cc013380) at galera/src/replicator_smm.cpp:433
#14 0x00007fc1f2aa6f8e in galera::ReplicatorSMM::process_trx (this=0x2724cb0, recv_ctx=0x7fc1cc0009a0, trx=0x7fc1cc013380) at galera/src/replicator_smm.cpp:1224
#15 0x00007fc1f2a8d705 in galera::GcsActionSource::dispatch (this=this@entry=0x2725330, recv_ctx=recv_ctx@entry=0x7fc1cc0009a0, act=..., exit_loop=@0x7fc1e863649d: false) at galera/src/gcs_action_source.cpp:116
#16 0x00007fc1f2a8dba9 in galera::GcsActionSource::process (this=0x2725330, recv_ctx=0x7fc1cc0009a0, exit_loop=@0x7fc1e863649d: false) at galera/src/gcs_action_source.cpp:181
#17 0x00007fc1f2aa7583 in galera::ReplicatorSMM::async_recv (this=0x2724cb0, recv_ctx=0x7fc1cc0009a0) at galera/src/replicator_smm.cpp:355
#18 0x0000000000643e97 in wsrep_replication_process (thd=0x7fc1cc0009a0) at /home/philips/git/mysql-wsrep/sql/wsrep_thd.cc:310
#19 0x00000000006246e2 in start_wsrep_THD (arg=0x643de9 <wsrep_replication_process(THD*)>) at /home/philips/git/mysql-wsrep/sql/mysqld.cc:5385
#20 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#21 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

**Comment by philip-galera** [comment]
```
--source include/galera_cluster.inc
--source include/have_innodb.inc

CREATE TABLE t1 (f1 INTEGER PRIMARY KEY);

--connection node_2

# Create applier failure

SET SESSION wsrep_on=OFF;
INSERT INTO t1 VALUES (1);

--connection node_1
INSERT INTO t1 VALUES (1);

--connection node_2
SELECT COUNT(*) = 1 FROM t1;

DROP TABLE t1;
```
