### ISSUE TITLE
Assertion or no error returned if SP is BF-aborted

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#191]
```
mysqld: /home/philips/git/mysql-wsrep-features-storedproc/sql/protocol.cc:1057: virtual bool Protocol_text::store_longlong(longlong, bool): Assertion `field_types == 0 || field_types[field_pos] == MYSQL_TYPE_LONGLONG' failed.

#7  0x0000003e9042da82 in __assert_fail () from /lib64/libc.so.6
#8  0x000000000072eb0c in Protocol_text::store_longlong (this=0x2687998, from=0, unsigned_flag=false) at /home/philips/git/mysql-wsrep-features-storedproc/sql/protocol.cc:1056
#9  0x0000000000673f32 in Item::send (this=0x7fe0400584a0, protocol=0x2687998, buffer=0x7fe08432d290) at /home/philips/git/mysql-wsrep-features-storedproc/sql/item.cc:6885
#10 0x000000000072e1af in Protocol::send_result_set_row (this=0x2687998, row_items=0x7fe040061998) at /home/philips/git/mysql-wsrep-features-storedproc/sql/protocol.cc:855
#11 0x0000000000798a65 in select_send::send_data (this=0x7fe04006add8, items=...) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_class.cc:2772
#12 0x00000000007acbe7 in JOIN::exec (this=0x7fe04006ae00) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_executor.cc:151
#13 0x000000000080bbec in mysql_execute_select (thd=0x26874c0, select_lex=0x7fe040061878, free_join=true) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_select.cc:1100
#14 0x000000000080be9a in mysql_select (thd=0x26874c0, tables=0x0, wild_num=0, fields=..., conds=0x0, order=0x7fe040061a40, group=0x7fe040061978, having=0x0, select_options=2149322240, result=0x7fe04006add8, unit=0x7fe040061230, select_lex=0x7fe040061878) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_select.cc:1221
#15 0x000000000080a06d in handle_select (thd=0x26874c0, result=0x7fe04006add8, setup_tables_done_option=0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_select.cc:110
#16 0x00000000007e467a in execute_sqlcom_select (thd=0x26874c0, all_tables=0x0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_parse.cc:5626
#17 0x00000000007dbeb0 in mysql_execute_command (thd=0x26874c0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_parse.cc:2951
#18 0x0000000000979e98 in sp_instr_stmt::exec_core (this=0x7fe0400585b0, thd=0x26874c0, nextp=0x7fe08432f048) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sp_instr.cc:904
#19 0x0000000000978d13 in sp_lex_instr::reset_lex_and_exec_core (this=0x7fe0400585b0, thd=0x26874c0, nextp=0x7fe08432f048, open_tables=false) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sp_instr.cc:390
#20 0x0000000000979634 in sp_lex_instr::validate_lex_and_execute_core (this=0x7fe0400585b0, thd=0x26874c0, nextp=0x7fe08432f048, open_tables=false) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sp_instr.cc:641
#21 0x0000000000979b39 in sp_instr_stmt::execute (this=0x7fe0400585b0, thd=0x26874c0, nextp=0x7fe08432f048) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sp_instr.cc:811
#22 0x000000000073e918 in sp_head::execute (this=0x7fe040050d30, thd=0x26874c0, merge_da_on_success=true) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sp_head.cc:648
#23 0x0000000000740645 in sp_head::execute_procedure (this=0x7fe040050d30, thd=0x26874c0, args=0x268a0c8) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sp_head.cc:1332
#24 0x00000000007e267c in mysql_execute_command (thd=0x26874c0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_parse.cc:5053
#25 0x00000000007e7987 in mysql_parse (thd=0x26874c0, rawbuf=0x7fe040004c50 "CALL p1()", length=9, parser_state=0x7fe0843306e0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_parse.cc:7025
#26 0x00000000007e6dde in wsrep_mysql_parse (thd=0x26874c0, rawbuf=0x7fe040004c50 "CALL p1()", length=9, parser_state=0x7fe0843306e0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_parse.cc:6773
#27 0x00000000007d8b31 in dispatch_command (command=COM_QUERY, thd=0x26874c0, packet=0x262b251 "", packet_length=9) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_parse.cc:1534
#28 0x00000000007d75df in do_command (thd=0x26874c0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_parse.cc:1118
#29 0x00000000007a2faf in do_handle_one_connection (thd_arg=0x26874c0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_connect.cc:1007
#30 0x00000000007a2ae5 in handle_one_connection (arg=0x26874c0) at /home/philips/git/mysql-wsrep-features-storedproc/sql/sql_connect.cc:916
#31 0x0000000000acfe56 in pfs_spawn_thread (arg=0x26d9e40) at /home/philips/git/mysql-wsrep-features-storedproc/storage/perfschema/pfs.cc:1860
#32 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#33 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

From the log:

```
2015-09-10 13:47:25 15657 [Note] WSREP: Winning thread:
   THD: 2, mode: applier, state: executing, conflict: no conflict, seqno: 4
   SQL: (null)
2015-09-10 13:47:25 15657 [Note] WSREP: Victim thread:
   THD: 7, mode: local, state: executing, conflict: no conflict, seqno: -1
   SQL: SELECT SLEEP(5)
2015-09-10 13:47:25 15657 [Note] WSREP: BF kill (1, seqno: 4), victim: (7) trx: 1290
2015-09-10 13:47:25 15657 [Note] WSREP: Aborting query: SELECT SLEEP(5)
2015-09-10 13:47:25 15657 [Note] WSREP: kill trx QUERY_EXEC for 1290
2015-09-10 13:47:25 15657 [Note] WSREP: kill query for: 7
2015-09-10 13:47:25 15657 [Note] WSREP: client rollback due to BF abort for (7), query: CALL p1()
2015-09-10 13:47:25 15657 [Note] WSREP: abort in exec query state, avoiding autocommit
2015-09-10 13:47:25 15657 [Note] WSREP: wsrep retrying AC query: CALL p1()
2015-09-10 13:47:25 15657 [Note] WSREP: cleanup transaction for LOCAL_STATE: START TRANSACTION
2015-09-10 13:47:25 15657 [Note] WSREP: skipping select metadata
```

Test case:

```
--source include/galera_cluster.inc
--source include/have_innodb.inc

CREATE TABLE t1 (f1 INTEGER PRIMARY KEY, f2 INTEGER) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1, 1);

DELIMITER |;
CREATE PROCEDURE p1 ()
BEGIN
        SET AUTOCOMMIT=OFF;

        START TRANSACTION;
        UPDATE t1 SET f2 = 2 WHERE f1 = 1;
        SELECT SLEEP(5);
        COMMIT;
END|
DELIMITER ;|

--connection node_1
--send CALL p1()

--connection node_2
UPDATE t1 SET f2 = 3 WHERE f1 = 1;

--connection node_1
--reap
```

**Comment by philip-galera** [comment]
If the deadlock error is to be delivered during a DML rather than select, it is eaten and the stored procedure succeeds even though the changes that it made are lost.

```
--source include/galera_cluster.inc
--source include/have_innodb.inc

CREATE TABLE t1 (f1 INTEGER PRIMARY KEY, f2 INTEGER) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1, 1);

CREATE TABLE t2 (f1 INTEGER) ENGINE=InnoDB;
INSERT INTO t2 VALUES (1);

DELIMITER |;
CREATE PROCEDURE p1 ()
BEGIN
        SET AUTOCOMMIT=OFF;
        START TRANSACTION;
        UPDATE t1 SET f2 = 2 WHERE f1 = 1;
        UPDATE t2 SET f1 = SLEEP(5) WHERE f1 = 1;
        COMMIT;
END|
DELIMITER ;|

--connection node_1
--send CALL p1()

--connection node_2
UPDATE t1 SET f2 = 3 WHERE f1 = 1;

--connection node_1
--reap

SELECT * FROM t1;

DROP PROCEDURE p1;
DROP TABLE t1;
DROP TABLE t2;
```
