### ISSUE TITLE
Assertion `!flags.finalized' failed in binlog_cache_data::finalize causes dozens of InnoDB tests to fail

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#2]
Running various InnoDB tests causes the following assertion:

```
mysqld: /home/philips/git/mysql-wsrep/sql/binlog.cc:1205: int binlog_cache_data::finalize(THD*, Log_event*): Assertion `!flags.finalized' failed.

#7  0x0000003e9042da82 in __assert_fail () from /lib64/libc.so.6
#8  0x0000000000a107d0 in binlog_cache_data::finalize (this=0x7fce8c0551d0, thd=0x2603820, end_event=0x7fcec03b8300) at /home/philips/git/mysql-wsrep/sql/binlog.cc:1205
#9  0x0000000000a0f833 in binlog_stmt_cache_data::finalize (this=0x7fce8c0551d0, thd=0x2603820) at /home/philips/git/mysql-wsrep/sql/binlog.cc:623
#10 0x0000000000a1d159 in MYSQL_BIN_LOG::commit (this=0x17f6e00 <mysql_bin_log>, thd=0x2603820, all=false) at /home/philips/git/mysql-wsrep/sql/binlog.cc:6476
#11 0x0000000000a2297e in wsrep_thd_binlog_commit (thd=0x2603820, all=false) at /home/philips/git/mysql-wsrep/sql/binlog.cc:9243
#12 0x000000000071d6a5 in TC_LOG_DUMMY::commit (this=0x17d24e8 <tc_log_dummy>, thd=0x2603820, all=false) at /home/philips/git/mysql-wsrep/sql/log.h:124
#13 0x000000000089be7e in trans_commit_stmt (thd=0x2603820) at /home/philips/git/mysql-wsrep/sql/transaction.cc:486
#14 0x00000000007e0511 in mysql_execute_command (thd=0x2603820) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:5444
#15 0x00000000007e39df in mysql_parse (thd=0x2603820, rawbuf=0x7fce8c004c30 "call mtr.add_suppression(\"InnoDB: Error: trying to open a table, but could not$\")", length=81, parser_state=0x7fcec03bb730) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6815
#16 0x00000000007e2fe6 in wsrep_mysql_parse (thd=0x2603820, rawbuf=0x7fce8c004c30 "call mtr.add_suppression(\"InnoDB: Error: trying to open a table, but could not$\")", length=81, parser_state=0x7fcec03bb730) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6595
#17 0x00000000007d5372 in dispatch_command (command=COM_QUERY, thd=0x2603820, packet=0x26cc5e1 "call mtr.add_suppression(\"InnoDB: Error: trying to open a table, but could not$\")", packet_length=81) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1525
#18 0x00000000007d3ec1 in do_command (thd=0x2603820) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1114
#19 0x000000000079fab7 in do_handle_one_connection (thd_arg=0x2603820) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:1007
#20 0x000000000079f5ed in handle_one_connection (arg=0x2603820) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:916
#21 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#22 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

For example:

```
./mysql-test-run.pl --suites=innodb --mysqld=--performance-schema=OFF --mysqld=--wsrep-provider=$WSREP_PROVIDER --skip-test-list=suite/innodb/t/galera.skip --no-check-testcases --mysqld=--wsrep-cluster-address="gcomm://" --force innodb.innodb-table-online --retry=0
```

**Comment by philip-galera** [comment]
This assertion affects dozens of tests from the innodb test suite.

**Comment by philip-galera** [comment]
There is also a duplicate report in LaunchPad: https://bugs.launchpad.net/codership-mysql/+bug/1371080

**Comment by sjaakola** [comment]
This issue happens when stored procedure does autocommit statement. Statement commit is entered two times: at statement end and next time at stored procedure end.

**Comment by sjaakola** [comment]
further analysis shows that this happens only with non-InnoDB statements, in this test specifically myisam tables

**Comment by philip-galera** [comment]
Test case:

```
--source include/galera_cluster.inc
--source include/have_innodb.inc

CREATE TABLE t1 (f1 INTEGER) ENGINE=InnoDB;
CREATE TABLE t2 (f1 INTEGER) ENGINE=MyISAM;
CREATE TABLE t3 (f1 INTEGER) ENGINE=MyISAM;

CREATE TRIGGER tr1 BEFORE INSERT ON t1 FOR EACH ROW INSERT INTO t3 VALUES (NEW.f1);

SET AUTOCOMMIT=OFF;
START TRANSACTION;
INSERT INTO t1 VALUES (1);
INSERT INTO t2 VALUES (1);
COMMIT;
```

**Comment by sjaakola** [comment]
This latter use case shows problem when having myisam statement inside innodb transaction. statement cache is not cleared in this case. A fix was pushed for this case today.
