### ISSUE TITLE
Galera initialization breaks when compiled with gcc 6 or --std=c++11

### ISSUE THREAD

**Issue by dciabrin** [mariadb-corporation/mysql-wsrep#267]
In the WSREP file `wsrep_mysqld.cc`, there is an unexpected const
qualifier on static global variable `cluster_uuid`.

```
static const wsrep_uuid_t cluster_uuid = WSREP_UUID_UNDEFINED;
```

From a compilation standpoint, this variable being initialized
from the value of another variable `WSREP_UUID_UNDEFINED`, the
C++ compiler used to perform the init at runtime, and to emit
variable `cluster_uuid` in segment .bss rather than .rodata.
Incidentally, that is why further write accesses to the address of
that variable succeed (e.g. in `wsrep_view_handler_cb()`).

Now starting with gcc 6.0, or when using gcc 5.x with -std=c++11,
the C++ compiler determines that `cluster_uuid` is being initialized
from a constant value, and so decides to emit variable `cluster_uuid`
in segment .rodata with value set at compile-time.

Any write to `cluster_uuid`'s address will end up in SIGSEGV, which prevents
using the Galera replication.

```
[root@fedora2 ~]# mysqld_safe --wsrep-new-cluster
160705 12:34:43 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
160705 12:34:43 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
160705 12:34:43 mysqld_safe WSREP: Running position recovery with --log_error='/var/lib/mysql/wsrep_recovery.X8ZxeH' --pid-file='/var/lib/mysql/fedora2.localdomain-recover.pid'
160705 12:34:46 mysqld_safe WSREP: Recovered position 00000000-0000-0000-0000-000000000000:-1
/usr/bin/mysqld_safe: line 188:  1799 Segmentation fault      (core dumped) nohup /usr/libexec/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plugin --user=mysql --wsrep_provider=/usr/lib64/galera/libgalera_smm.so --wsrep-new-cluster --log-error=/var/log/mariadb/mariadb.log --pid-file=/var/run/mariadb/mariadb.pid --socket=/var/lib/mysql/mysql.sock --wsrep_start_position=00000000-0000-0000-0000-000000000000:-1 < /dev/null >> /var/log/mariadb/mariadb.log 2>&1
160705 12:34:46 mysqld_safe mysqld from pid file /var/run/mariadb/mariadb.pid ended

[root@fedora2 ~]# gdb /usr/libexec/mysqld /tmp/corefiles/core.2221 
[...]
Core was generated by `/usr/libexec/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/l'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbf7d742def in pthread_kill () from /lib64/libpthread.so.0
[Current thread is 1 (Thread 0x7fbf785aab00 (LWP 2227))]
Missing separate debuginfos, use: dnf debuginfo-install mariadb-server-10.1.14-1.fc24.x86_64
(gdb) bt
#0  0x00007fbf7d742def in pthread_kill () from /lib64/libpthread.so.0
#1  0x000055e7c7b18cd5 in handle_fatal_signal ()
#2  <signal handler called>
#3  0x000055e7c7ab728e in wsrep_view_handler_cb(void*, void*, wsrep_view_info const*, char const*, unsigned long, void**, unsigned long*) ()
#4  0x00007fbf7891678a in galera::ReplicatorSMM::process_conf_change(void*, wsrep_view_info const&, int, galera::Replicator::State, long) ()
   from /usr/lib64/galera/libgalera_smm.so
#5  0x00007fbf788efa7b in galera::GcsActionSource::dispatch(void*, gcs_action const&, bool&) () from /usr/lib64/galera/libgalera_smm.so
#6  0x00007fbf788f1166 in galera::GcsActionSource::process(void*, bool&) () from /usr/lib64/galera/libgalera_smm.so
#7  0x00007fbf78915f46 in galera::ReplicatorSMM::async_recv(void*) () from /usr/lib64/galera/libgalera_smm.so
#8  0x00007fbf7893061e in galera_recv () from /usr/lib64/galera/libgalera_smm.so
#9  0x000055e7c7ac63f7 in wsrep_replication_process(THD*) ()
#10 0x000055e7c7ab5ef4 in start_wsrep_THD ()
#11 0x00007fbf7d73c5ba in start_thread () from /lib64/libpthread.so.0
#12 0x00007fbf7bc4f7cd in clone () from /lib64/libc.so.6
```

**Comment by ayurchen** [comment]
Fixed in https://github.com/codership/mysql-wsrep/issues/274
