### ISSUE TITLE
Aborting trx leaves behind open tables in cache leading to assert

### ISSUE THREAD

**Issue by kbauskar** [mariadb-corporation/mysql-wsrep#275]
1. Start 2 node cluster (n1, n2)
2. On n1 create table t1.
3. Execute any statement that will open the table. Let's use simplest "handler t1 open t1"
4. While the statement is busy opening the table execute "DROP table t1" on n2 such that it is replicated at same time on n1. (This we can achieve using DEBUG_SYNC).
5. DROP table being replicated transaction will cause "handler t1...." to abort which probably leaves behind open tables in cache and so when DROP table try to proceed after handler is aborted, DROP table hit the said assert.

[Note: Problem persist with other DDL too. Like tcs also tried RENAME table as the base issue is with the rollback and not the DDL statement. Any DDL that will try needs cleaned up cache.] 

```
#6  0x00007fe5d646e03d in __assert_fail_base (fmt=0x7fe5d65d0028 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xfc1178 "cache_el[i]->used_tables.is_empty()", file=file@entry=0xfc1128 "/opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/table_cache.cc", line=line@entry=364, function=function@entry=0xfc1340 <Table_cache_manager::free_table(THD*, enum_tdc_remove_table_type, TABLE_SHARE*)::__PRETTY_FUNCTION__> "void Table_cache_manager::free_table(THD*, enum_tdc_remove_table_type, TABLE_SHARE*)") at assert.c:92
#7  0x00007fe5d646e0f2 in __GI___assert_fail (assertion=0xfc1178 "cache_el[i]->used_tables.is_empty()", file=0xfc1128 "/opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/table_cache.cc", line=364, function=0xfc1340 <Table_cache_manager::free_table(THD*, enum_tdc_remove_table_type, TABLE_SHARE*)::__PRETTY_FUNCTION__> "void Table_cache_manager::free_table(THD*, enum_tdc_remove_table_type, TABLE_SHARE*)") at assert.c:101
#8  0x00000000008ebb3e in Table_cache_manager::free_table (this=0x18b2280 <table_cache_manager>, thd=0x7fe5b40009a0, remove_type=TDC_RT_REMOVE_ALL, share=0x7fe584033ef0) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/table_cache.cc:364
#9  0x00000000007ad077 in tdc_remove_table (thd=0x7fe5b40009a0, remove_type=TDC_RT_REMOVE_ALL, db=0x7fe5b4009258 "test", table_name=0x7fe5b4008cc0 "t1", has_lock=false) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/sql_base.cc:9353
#10 0x00000000008820d3 in mysql_rm_table (thd=0x7fe5b40009a0, tables=0x7fe5b4008cf8, if_exists=0 '\000', drop_temporary=0 '\000') at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/sql_table.cc:2140
#11 0x0000000000816a87 in mysql_execute_command (thd=0x7fe5b40009a0) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/sql_parse.cc:4069
#12 0x000000000082065b in mysql_parse (thd=0x7fe5b40009a0, rawbuf=0x7fe5b40367b9 "drop table t1", length=13, parser_state=0x7fe5c63e74b0) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/sql_parse.cc:7111
#13 0x0000000000a5e6bf in Query_log_event::do_apply_event (this=0x7fe5b4036c50, rli=0x7fe5b400bcd0, query_arg=0x7fe5b40367b9 "drop table t1", q_len_arg=13) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/log_event.cc:4837
#14 0x0000000000a5d93b in Query_log_event::do_apply_event (this=0x7fe5b4036c50, rli=0x7fe5b400bcd0) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/log_event.cc:4561
#15 0x0000000000a596c2 in Log_event::apply_event (this=0x7fe5b4036c50, rli=0x7fe5b400bcd0) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/log_event.cc:3121
#16 0x00000000006519b6 in wsrep_apply_events (thd=0x7fe5b40009a0, events_buf=0x7fe5c955472f, buf_len=0) at /opt/projects/codebase/non-forked-codership/gxc/mysql-wsrep/sql/wsrep_applier.cc:147
```

Here is the needed patch to reproduce the issue with debug_sync.
I tested this with 5.6.31 version.

---

```
diff --git a/mysql-test/suite/galera/t/abort_leaves_behind_open_tables.test b/mysql-test/suite/galera/t/abort_leaves_behind_open_tables.test
new file mode 100644
index 0000000..7181fc3
--- /dev/null
+++ b/mysql-test/suite/galera/t/abort_leaves_behind_open_tables.test
@@ -0,0 +1,36 @@
+#
+#
+--source include/galera_cluster.inc
+--source include/have_innodb.inc
+--source include/have_debug_sync.inc
+
+CREATE TABLE t1 (id INT PRIMARY KEY) ENGINE=InnoDB;
+
+--connection node_2
+--echo #node-2
+--let $wait_condition = SELECT COUNT(*) = 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 't1';
+--source include/wait_condition.inc
+
+--connection node_1
+--echo #node-1
+SET DEBUG_SYNC = 'innodb_delay_open_table WAIT_FOR continue';
+--send handler t1 open as t1;
+
+--connection node_2
+--echo #node-2
+drop table t1;
+#rename table t1 to t2;
+
+--connect node_1a, 127.0.0.1, root, , test, $NODE_MYPORT_1
+--connection node_1a
+SET DEBUG_SYNC= 'now SIGNAL continue';
+
+--connection node_1
+--echo #node-1
+--reap
+--sleep 2
+select * from inforomation_schema.processlist;
+#--let $wait_condition = SELECT COUNT(*) = 1 FROM INFORMATION_SCHEMA.PROCESSLIST WHERE STATE = 'Waiting for table metadata lock'
+#--source include/wait_condition.inc
+--sleep 2
+show tables;
diff --git a/storage/innobase/handler/ha_innodb.cc b/storage/innobase/handler/ha_innodb.cc
index 9c22c3f..c9f2db4 100644
--- a/storage/innobase/handler/ha_innodb.cc
+++ b/storage/innobase/handler/ha_innodb.cc
@@ -5680,6 +5680,7 @@ ha_innobase::open(
    dict_err_ignore_t   ignore_err = DICT_ERR_IGNORE_NONE;

    DBUG_ENTER("ha_innobase::open");
+   DEBUG_SYNC(ha_thd(), "innodb_delay_open_table");

    UT_NOT_USED(mode);
    UT_NOT_USED(test_if_locked);
```

**Comment by philip-galera** [comment]
I am unable to reproduce this assertion with any other statement but HANDLER. Have you seen it in other contexts?

Simplified test case:

```
--source include/galera_cluster.inc
--source include/have_innodb.inc
--source include/have_debug_sync.inc

CREATE TABLE t1 (id INT PRIMARY KEY) ENGINE=InnoDB;

--connection node_2
--let $wait_condition = SELECT COUNT(*) = 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 't1';
--source include/wait_condition.inc

--connection node_1
SET DEBUG_SYNC = 'innodb_delay_open_table WAIT_FOR continue';
--send handler t1 open as t1;

--connection node_2
drop table t1;
```

InnoDB patch at correct position for mysql-wsrep:

```
diff --git a/storage/innobase/handler/ha_innodb.cc b/storage/innobase/handler/ha_innodb.cc
index c97714a..e155d42 100644
--- a/storage/innobase/handler/ha_innodb.cc
+++ b/storage/innobase/handler/ha_innodb.cc
@@ -4938,6 +4938,7 @@ ha_innobase::open(
        dict_err_ignore_t       ignore_err = DICT_ERR_IGNORE_NONE;

        DBUG_ENTER("ha_innobase::open");
+        DEBUG_SYNC(ha_thd(), "innodb_delay_open_table");

        UT_NOT_USED(mode);
        UT_NOT_USED(test_if_locked);
```

**Comment by philip-galera** [comment]
@sjaakola : FYI, see commit 89e2c805c611c58c416ca57d3c834b640eb67d2e in -bugs

**Comment by kbauskar** [comment]
@philip-galera 
As part of random testing we saw it even with 2 replicated applier with one likely executing DML and other DDL. But given that it was random testing we couldn't exactly reproduce that scenario.
(I will try more when I get some more time).
