### ISSUE TITLE
InnoDB: Failing assertion: xid_seqno > trx_sys_cur_xid_seqno in trx_sys_update_wsrep_checkpoint with mysqldump IST

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#33]
If IST is forced by temporarily setting wsrep_provider to "none" and then setting it back to its original value, the node asserts as follows:

```
2014-12-17 16:30:13 58763 [Note] WSREP: Shifting PRIMARY -> JOINER (TO: 5)
2014-12-17 16:30:13 58763 [Note] WSREP: Requesting state transfer: success, donor: 0
2014-12-17 16:30:13 7f7e383fc700  InnoDB: Assertion failure in thread 140180086310656 in file trx0sys.cc line 353
InnoDB: Failing assertion: xid_seqno > trx_sys_cur_xid_seqno

#5  0x0000003e90436a8a in abort () from /lib64/libc.so.6
#6  0x0000000000d0d1d9 in trx_sys_update_wsrep_checkpoint (xid=0x7f7e383f9c30, sys_header=0x7f7e38dd4026 "", mtr=0x7f7e383f91a0) at /home/philips/git/mysql-wsrep/storage/innobase/trx/trx0sys.cc:353
#7  0x0000000000bacd98 in innobase_wsrep_set_checkpoint (hton=0x2535ca0, xid=0x7f7e383f9c30) at /home/philips/git/mysql-wsrep/storage/innobase/handler/ha_innodb.cc:16988
#8  0x000000000063a72c in set_SE_checkpoint (unused=0x0, plugin=0x7f7e383f9bc8, arg=0x7f7e383f9c30) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:165
#9  0x0000000000807a24 in plugin_foreach_with_mask (thd=0x0, func=0x63a5e6 <set_SE_checkpoint(THD*, plugin_ref, void*)>, type=1, state_mask=4294967287, arg=0x7f7e383f9c30) at /home/philips/git/mysql-wsrep/sql/sql_plugin.cc:2162
#10 0x000000000063a761 in wsrep_set_SE_checkpoint (xid=0x7f7e383f9c30) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:172
#11 0x0000000000646a8f in wsrep_set_local_position (value=0x7f7de4005080 "b8c6df20-85f0-11e4-aabd-d2bdcbd94cf4:4") at /home/philips/git/mysql-wsrep/sql/wsrep_var.cc:158
#12 0x0000000000646b15 in wsrep_start_position_update (self=0x18377c0 <Sys_wsrep_start_position>, thd=0x27267d0, type=OPT_GLOBAL) at /home/philips/git/mysql-wsrep/sql/wsrep_var.cc:166
#13 0x000000000074326a in sys_var::update (this=0x18377c0 <Sys_wsrep_start_position>, thd=0x27267d0, var=0x7f7de4005458) at /home/philips/git/mysql-wsrep/sql/set_var.cc:194
#14 0x0000000000744312 in set_var::update (this=0x7f7de4005458, thd=0x27267d0) at /home/philips/git/mysql-wsrep/sql/set_var.cc:670
#15 0x0000000000743eea in sql_set_variables (thd=0x27267d0, var_list=0x27297c8) at /home/philips/git/mysql-wsrep/sql/set_var.cc:573
#16 0x00000000007f4aca in mysql_execute_command (thd=0x27267d0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:4075
#17 0x00000000007fcd81 in mysql_parse (thd=0x27267d0, rawbuf=0x7f7de40051f0 "SET GLOBAL wsrep_start_position='b8c6df20-85f0-11e4-aabd-d2bdcbd94cf4:4'", length=72, parser_state=0x7f7e383fb6e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6815
#18 0x00000000007fc342 in wsrep_mysql_parse (thd=0x27267d0, rawbuf=0x7f7de40051f0 "SET GLOBAL wsrep_start_position='b8c6df20-85f0-11e4-aabd-d2bdcbd94cf4:4'", length=72, parser_state=0x7f7e383fb6e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6595
#19 0x00000000007edf8f in dispatch_command (command=COM_QUERY, thd=0x27267d0, packet=0x2690e11 "SET GLOBAL wsrep_start_position='b8c6df20-85f0-11e4-aabd-d2bdcbd94cf4:4'", packet_length=72) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1525
#20 0x00000000007eca4f in do_command (thd=0x27267d0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1114
#21 0x00000000007b5c6a in do_handle_one_connection (thd_arg=0x27267d0) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:1007
#22 0x00000000007b577f in handle_one_connection (arg=0x27267d0) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:916
#23 0x0000000000af77b6 in pfs_spawn_thread (arg=0x2685c30) at /home/philips/git/mysql-wsrep/storage/perfschema/pfs.cc:1860
#24 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#25 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

**Comment by philip-galera** [comment]
Using the new --source files just pushed:

.test file:

```
--source include/galera_cluster.inc
--source include/have_innodb.inc

--source suite/galera/include/galera_sst_set_mysqldump.inc

--source suite/galera/include/galera_st_disconnect_slave.inc

--source suite/galera/include/galera_sst_restore.inc
```

.cnf file:

```
!include ../galera_2nodes.cnf

[mysqld.1]
wsrep_provider_options='base_port=@mysqld.1.#galera_port;pc.ignore_sb=true'

[mysqld.2]
wsrep_provider_options='base_port=@mysqld.2.#galera_port;pc.ignore_sb=true'
```

**Comment by ayurchen** [comment]
Looks like https://github.com/codership/mysql-wsrep/commit/07fab8c7dad76411d5d822631c75ad1c15eeeeff fixes the issue
