### ISSUE TITLE
5.7: Multimaster hang with innodb-thread-concurrency=8

### ISSUE THREAD

**Issue by temeo** [mariadb-corporation/mysql-wsrep#364]
**Steps to reproduce:**
1. Configure cluster nodes with `innodb-thread-concurrency=8`
2. Run multimaster sysbench load against cluster with such a parameters that high number of write conflicts are produced (e.g. tables: 4, rows: 4, connections: 64).
3. Observe how client connections get stuck on at one of the nodes in
```|  8 | test        | 192.168.20.5:49152 | sysbench | Query   |  107 | statistics         | SELECT c FROM sbtest3 WHERE id=4676 |
|  9 | test        | 192.168.20.5:49148 | sysbench | Query   |  107 | statistics         | SELECT c FROM sbtest2 WHERE id=4957 |
```
4. Gdb backtrace shows that the threads are hanging in trying to access InnoDB:
```
Thread 66 (Thread 0x7f6468312700 (LWP 13987)):
#0  0x00007f648718cc60 in __GI___nanosleep (
    requested_time=requested_time@entry=0x7f646830f640, 
    remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x000056189f40e19f in os_thread_sleep (tm=<optimized out>)
    at /home/teemu/work/git/mysql-wsrep-bugs/storage/innobase/os/os0thread.cc:287
#2  0x000056189f4b4f2e in srv_conc_enter_innodb_with_atomics (
    trx=<optimized out>)
    at /home/teemu/work/git/mysql-wsrep-bugs/storage/innobase/srv/srv0conc.cc:235
#3  srv_conc_enter_innodb (prebuilt=<optimized out>)
    at /home/teemu/work/git/mysql-wsrep-bugs/storage/innobase/srv/srv0conc.cc:279
#4  0x000056189f38968c in ha_innobase::index_read (this=0x7f642804db00, 
    buf=0x7f642804df10 "\377", key_ptr=0x0, key_len=<optimized out>, 
    find_flag=<optimized out>)
    at /home/teemu/work/git/mysql-wsrep-bugs/storage/innobase/handler/ha_innodb.cc:9487
```

**Comment by mkaruza** [comment]
Will be fixed in next release.
