### ISSUE TITLE
Crash in galera_to_execute_end when wsrep_OSU_method is changed from RSU to TOI during a DDL

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#90]
```
Thread 1 (Thread 0x7fa6184c3700 (LWP 51329)):
#0  0x0000003e90c0dccc in pthread_kill () from /lib64/libpthread.so.0
#1  0x0000000000ab57a1 in my_write_core (sig=11) at /home/philips/git/mysql-wsrep/mysys/stacktrace.c:422
#2  0x00000000007465c4 in handle_fatal_signal (sig=11) at /home/philips/git/mysql-wsrep/sql/signal_handler.cc:230
#3  <signal handler called>
#4  0x0000003e90c09ab4 in pthread_mutex_lock () from /lib64/libpthread.so.0
#5  0x00007fa625d91ccd in galera_to_execute_end (gh=<optimized out>, conn_id=7) at galera/src/wsrep_provider.cpp:780
#6  0x000000000063f92f in wsrep_TOI_end (thd=0x381d870) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:1324
#7  0x0000000000640548 in wsrep_to_isolation_end (thd=0x381d870) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:1480
#8  0x00000000007fa84a in mysql_execute_command (thd=0x381d870) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:5501
#9  0x00000000007fe24c in mysql_parse (thd=0x381d870, rawbuf=0x7fa5d8004c50 "ALTER TABLE t1 ADD COLUMN f2 INTEGER", length=36, parser_state=0x7fa6184c26e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6960
#10 0x00000000007fd658 in wsrep_mysql_parse (thd=0x381d870, rawbuf=0x7fa5d8004c50 "ALTER TABLE t1 ADD COLUMN f2 INTEGER", length=36, parser_state=0x7fa6184c26e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6707
#11 0x00000000007eee68 in dispatch_command (command=COM_QUERY, thd=0x381d870, packet=0x3891701 "ALTER TABLE t1 ADD COLUMN f2 INTEGER;", packet_length=37) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1525
#12 0x00000000007ed928 in do_command (thd=0x381d870) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1114
#13 0x00000000007b6acc in do_handle_one_connection (thd_arg=0x381d870) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:1007
#14 0x00000000007b65e1 in handle_one_connection (arg=0x381d870) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:916
#15 0x0000000000afa300 in pfs_spawn_thread (arg=0x3722e90) at /home/philips/git/mysql-wsrep/storage/perfschema/pfs.cc:1860
#16 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#17 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

Test case:

```
--source include/galera_cluster.inc
--source include/have_innodb.inc
--source include/have_debug_sync.inc

CREATE TABLE t1 (f1 INTEGER PRIMARY KEY) Engine=InnoDB;

--connection node_1
SET GLOBAL wsrep_OSU_method = "RSU";
SET DEBUG_SYNC = 'alter_table_before_open_tables WAIT_FOR continue';
--send ALTER TABLE t1 ADD COLUMN f2 INTEGER;


--connect node_1a, 127.0.0.1, root, , test, $NODE_MYPORT_1
--connection node_1a

--sleep 1
--let $wait_condition = SELECT COUNT(*) = 1 FROM INFORMATION_SCHEMA.PROCESSLIST WHERE STATE = 'debug sync point: alter_table_before_open_tables'
--source include/wait_condition.inc

SET GLOBAL wsrep_OSU_method = "TOI";
SET DEBUG_SYNC= 'now SIGNAL continue';

--connection node_1
--reap

SELECT COUNT(*) = 2 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 't1';

--connection node_2
# The ALTER above is not visible on node_2
SELECT COUNT(*) = 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 't1';

--connection node_1
DROP TABLE t1;
```

**Comment by philip-galera** [comment]
Doing it the other way around causes an assertion:

```
mysqld: galera/src/replicator_smm.cpp:1600: virtual void galera::ReplicatorSMM::resume(): Assertion `pause_seqno_ != (-1)' failed.

#7  0x0000003e9042da82 in __assert_fail () from /lib64/libc.so.6
#8  0x00007f5db50f80a7 in galera::ReplicatorSMM::resume (this=0x2230b60) at galera/src/replicator_smm.cpp:1600
#9  0x00007f5db510c763 in galera_resume (gh=<optimized out>) at galera/src/wsrep_provider.cpp:979
#10 0x000000000063ffd7 in wsrep_RSU_end (thd=0x24c9ff0) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:1389
#11 0x0000000000640556 in wsrep_to_isolation_end (thd=0x24c9ff0) at /home/philips/git/mysql-wsrep/sql/wsrep_mysqld.cc:1481
#12 0x00000000007fa84a in mysql_execute_command (thd=0x24c9ff0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:5501
#13 0x00000000007fe24c in mysql_parse (thd=0x24c9ff0, rawbuf=0x7f5d64004c50 "ALTER TABLE t1 ADD COLUMN f2 INTEGER", length=36, parser_state=0x7f5d91ffa6e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6960
#14 0x00000000007fd658 in wsrep_mysql_parse (thd=0x24c9ff0, rawbuf=0x7f5d64004c50 "ALTER TABLE t1 ADD COLUMN f2 INTEGER", length=36, parser_state=0x7f5d91ffa6e0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:6707
#15 0x00000000007eee68 in dispatch_command (command=COM_QUERY, thd=0x24c9ff0, packet=0x255b3e1 "ALTER TABLE t1 ADD COLUMN f2 INTEGER;", packet_length=37) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1525
#16 0x00000000007ed928 in do_command (thd=0x24c9ff0) at /home/philips/git/mysql-wsrep/sql/sql_parse.cc:1114
#17 0x00000000007b6acc in do_handle_one_connection (thd_arg=0x24c9ff0) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:1007
#18 0x00000000007b65e1 in handle_one_connection (arg=0x24c9ff0) at /home/philips/git/mysql-wsrep/sql/sql_connect.cc:916
#19 0x0000000000afa300 in pfs_spawn_thread (arg=0x253be60) at /home/philips/git/mysql-wsrep/storage/perfschema/pfs.cc:1860
#20 0x0000003e90c0753a in start_thread () from /lib64/libpthread.so.0
#21 0x0000003e905045fd in clone () from /lib64/libc.so.6
```

Test case:

```
--source include/galera_cluster.inc
--source include/have_innodb.inc
--source include/have_debug_sync.inc

CREATE TABLE t1 (f1 INTEGER PRIMARY KEY) Engine=InnoDB;

--connection node_1
SET GLOBAL wsrep_OSU_method = "TOI";
SET DEBUG_SYNC = 'alter_table_before_open_tables WAIT_FOR continue';
--send ALTER TABLE t1 ADD COLUMN f2 INTEGER;


--connect node_1a, 127.0.0.1, root, , test, $NODE_MYPORT_1
--connection node_1a

SET SESSION wsrep_sync_wait = 0;

--let $wait_condition = SELECT COUNT(*) = 1 FROM INFORMATION_SCHEMA.PROCESSLIST WHERE STATE = 'debug sync point: alter_table_before_open_tables'
--source include/wait_condition.inc

SET GLOBAL wsrep_OSU_method = "RSU";
SET DEBUG_SYNC= 'now SIGNAL continue';

--connection node_1
--reap

SELECT COUNT(*) = 2 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 't1';
INSERT INTO t1 VALUES (1,2);

--connection node_2
The ALTER above is visible on node_2
SELECT COUNT(*) = 2 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 't1';
INSERT INTO t1 VALUES (3,4);

--connection node_1
DROP TABLE t1;
```

**Comment by philip-galera** [comment]
Test cases passed and pushed.
