### ISSUE TITLE
Regression: Crash in inline_mysql_mutex_lock with GTID

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#98]
The three MTR tests for GTID now all crash as follows:

```
#3  <signal handler called>
#4  0x0000000000a04765 in inline_mysql_mutex_lock (that=0x51, src_file=0x1066440 "/var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/rpl_gtid.h", src_line=652) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/include/mysql/psi/mysql_thread.h:659
#5  0x0000000000a05857 in Mutex_cond_array::lock (this=0x1d53290, n=-1) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/rpl_gtid.h:652
#6  0x0000000000a05be0 in Gtid_state::lock_sidno (this=0x1d53280, sidno=-1) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/rpl_gtid.h:2214
#7  0x0000000000a069af in Group_cache::generate_automatic_gno (this=0x7fc52803bdf0, thd=0x7fc5280009a0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/rpl_gtid_cache.cc:166
#8  0x0000000000a35b9e in gtid_before_write_cache (thd=0x7fc5280009a0, cache_data=0x7fc52803bcd0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/binlog.cc:1117
#9  0x0000000000a3628a in binlog_cache_data::flush (this=0x7fc52803bcd0, thd=0x7fc5280009a0, bytes_written=0x7fc534676800, wrote_xid=0x7fc53467683b) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/binlog.cc:1269
#10 0x0000000000a4b9cb in binlog_cache_mngr::flush (this=0x7fc52803bcd0, thd=0x7fc5280009a0, bytes_written=0x7fc534676840, wrote_xid=0x7fc53467683b) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/binlog.cc:782
#11 0x0000000000a43d57 in MYSQL_BIN_LOG::flush_thread_caches (this=0x1835080 <mysql_bin_log>, thd=0x7fc5280009a0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/binlog.cc:6634
#12 0x0000000000a43ef0 in MYSQL_BIN_LOG::process_flush_stage_queue (this=0x1835080 <mysql_bin_log>, total_bytes_var=0x7fc534676948, rotate_var=0x7fc53467692e, out_queue_var=0x7fc534676950) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/binlog.cc:6690
#13 0x0000000000a44c05 in MYSQL_BIN_LOG::ordered_commit (this=0x1835080 <mysql_bin_log>, thd=0x7fc5280009a0, all=false, skip_commit=false) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/binlog.cc:7128
#14 0x0000000000a43c21 in MYSQL_BIN_LOG::commit (this=0x1835080 <mysql_bin_log>, thd=0x7fc5280009a0, all=false) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/binlog.cc:6601
#15 0x00000000008b3ecb in trans_commit_stmt (thd=0x7fc5280009a0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/transaction.cc:486
#16 0x00000000007ec102 in mysql_execute_command (thd=0x7fc5280009a0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/sql_parse.cc:5460
#17 0x00000000007efc1e in mysql_parse (thd=0x7fc5280009a0, rawbuf=0x7fc528010499 "CREATE TABLE t1 (f1 INT PRIMARY KEY)", length=36, parser_state=0x7fc534679580) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/sql_parse.cc:6976
#18 0x0000000000a1244b in Query_log_event::do_apply_event (this=0x7fc52800f6c0, rli=0x7fc52800bcb0, query_arg=0x7fc528010499 "CREATE TABLE t1 (f1 INT PRIMARY KEY)", q_len_arg=36) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/log_event.cc:4837
#19 0x0000000000a11813 in Query_log_event::do_apply_event (this=0x7fc52800f6c0, rli=0x7fc52800bcb0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/log_event.cc:4566
#20 0x0000000000a0d929 in Log_event::apply_event (this=0x7fc52800f6c0, rli=0x7fc52800bcb0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/log_event.cc:3128
#21 0x000000000063f593 in wsrep_apply_events (thd=0x7fc5280009a0, events_buf=0x7fc536fe5617, buf_len=0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/wsrep_applier.cc:154
#22 0x000000000063fc9c in wsrep_apply_cb (ctx=0x7fc5280009a0, buf=0x7fc536fe5617, buf_len=99, flags=5, meta=0x7fc53467acc0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/wsrep_applier.cc:251
#23 0x00007fc53fae703b in galera::TrxHandle::apply (this=this@entry=0x7fc52800f010, recv_ctx=recv_ctx@entry=0x7fc5280009a0, apply_cb=apply_cb@entry=0x63f9bf <wsrep_apply_cb(void*, void const*, unsigned long, unsigned int, wsrep_trx_meta const*)>, meta=...) at galera/src/trx_handle.cpp:315
#24 0x00007fc53fb1123a in apply_trx_ws (recv_ctx=recv_ctx@entry=0x7fc5280009a0, apply_cb=0x63f9bf <wsrep_apply_cb(void*, void const*, unsigned long, unsigned int, wsrep_trx_meta const*)>, commit_cb=0x64009e <wsrep_commit_cb(void*, unsigned int, wsrep_trx_meta const*, bool*, bool)>, trx=..., meta=...) at galera/src/replicator_smm.cpp:38
#25 0x00007fc53fb13afb in galera::ReplicatorSMM::apply_trx (this=this@entry=0x1cea890, recv_ctx=recv_ctx@entry=0x7fc5280009a0, trx=trx@entry=0x7fc52800f010) at galera/src/replicator_smm.cpp:432
#26 0x00007fc53fb1621e in galera::ReplicatorSMM::process_trx (this=0x1cea890, recv_ctx=0x7fc5280009a0, trx=0x7fc52800f010) at galera/src/replicator_smm.cpp:1223
#27 0x00007fc53fafc615 in galera::GcsActionSource::dispatch (this=this@entry=0x1ceaf10, recv_ctx=recv_ctx@entry=0x7fc5280009a0, act=..., exit_loop=@0x7fc53467b43d: false) at galera/src/gcs_action_source.cpp:116
#28 0x00007fc53fafca99 in galera::GcsActionSource::process (this=0x1ceaf10, recv_ctx=0x7fc5280009a0, exit_loop=@0x7fc53467b43d: false) at galera/src/gcs_action_source.cpp:181
#29 0x00007fc53fb16853 in galera::ReplicatorSMM::async_recv (this=0x1cea890, recv_ctx=0x7fc5280009a0) at galera/src/replicator_smm.cpp:354
#30 0x0000000000641562 in wsrep_replication_process (thd=0x7fc5280009a0) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/wsrep_thd.cc:309
#31 0x0000000000620aa8 in start_wsrep_THD (arg=0x6414a5 <wsrep_replication_process(THD*)>) at /var/lib/jenkins/workspace/mtr-galera-mysql-5.6/mysql-wsrep/sql/mysqld.cc:5376
#32 0x00007fc54493d182 in start_thread (arg=0x7fc53467c700) at pthread_create.c:312
#33 0x00007fc543e4a00d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111


#4  0x0000000000a0a257 in inline_mysql_mutex_lock (that=0x51, 
    src_file=0xfde500 "/home/philips/git/mysql-wsrep/sql/rpl_gtid.h", src_line=652)
    at /home/philips/git/mysql-wsrep/include/mysql/psi/mysql_thread.h:659
659   if (that->m_psi != NULL)
(gdb) list
654   )
655 {
656   int result;
657 
658 #ifdef HAVE_PSI_MUTEX_INTERFACE
659   if (that->m_psi != NULL)
660   {
661     /* Instrumentation start */
662     PSI_mutex_locker *locker;
663     PSI_mutex_locker_state state;
(gdb) print that
$1 = (mysql_mutex_t *) 0x51
(gdb) print that->m_psi
Cannot access memory at address 0x79

```

To reproduce:

```
perl mysql-test-run.pl --suite galera  galera.galera_gtid galera.galera_as_master_gtid galera.galera_as_master_gtid_change_master
```

**Comment by philip-galera** [comment]
Seems this commit may be the problem:

https://github.com/codership/mysql-wsrep/pull/95

**Comment by ayurchen** [comment]
I think this can be closed?
